# Split 1

## Hebbian learning (3.1)

In [5]:
import numpy as np

patterns = np.array(
    [
        [-1, -1, 1, -1, 1, -1, -1, 1],
        [-1, -1, -1, -1, -1, 1, -1, -1],
        [-1, 1, 1, -1, -1, 1, -1, 1],
    ]
)

cues = np.array(
    [
        [1, -1, 1, -1, 1, -1, -1, 1],
        [1, 1, -1, -1, -1, 1, -1, -1],
        [1, 1, 1, -1, 1, 1, -1, 1],
    ]
)

In [6]:
from tools import HopfieldNetwork

h = HopfieldNetwork(8)
h.fit(patterns)

out = h.recall(cues)
print(out)

[[-1. -1.  1. -1.  1. -1. -1.  1.]
 [-1.  1. -1. -1. -1.  1. -1. -1.]
 [-1.  1.  1. -1.  1.  1. -1.  1.]]
